### ISSUE TITLE
Root element is missing error?

### ISSUE THREAD

**Issue by y-blip** [Black-Dragon131/AmongUsModManager#3]
It seems to have installed correctly but i keep getting a root element is missing error...
here is the pastebin https://pastebin.com/sBY4EKk5 if you need more info then let me know

**Comment by y-blip** [comment]
it doesn't seem to be a .NET framework issue as i reinstalled 4.8 after installing 4.7.2 and nothing changed

**Comment by Black-Dragon131** [comment]
Hello y-blip,

this could be a corrupted settings.xml. Try to delete the complete AmongUsModManager folder at
 C:\Users\<USERNAME>\AppData\Roaming\

**Comment by y-blip** [comment]
No fix... i think but at least there is a new error:
"The exception unknown software exception (0xe0434352) occurred in the application at location 0xfc99b87d."
The error window is called: 
".NET-BroadcastEventWindow.4.0.0.0.141b42a.0:AmongUsModManager.exe-Application Error" sorry if i'm becoming high maintenance

**Comment by Black-Dragon131** [comment]
Which version of AUMM have you installed? Can you check eventlogs for a more specific error?

Also try this debug version: https://aumm.black-dragon131.de/AmongUsModManager_debug.exe
Just put it at the same folder where you installed AUMM.
It should create a file "exceptions.log" under C:\Users\USERNAME\AppData\Roaming\


>  sorry if i'm becoming high maintenance

It' s fine. If no one opens issues how can I make it more stable for everyone? ;)

**Comment by y-blip** [comment]
"MyHandler caught : The request was aborted: Could not create SSL/TLS secure channel.
Runtime terminating: True"
thats what the exception.log says and it was the latest version at the time

**Comment by Black-Dragon131** [comment]
Hello y-blip,
thanks for the feedback. This means AUMM on you PC can' t establish a secure https connection to my server.
My server only accepts TLS >= 1.2.
What' s you Windows version?

I added some code which should force AUMM to use 1.2 for the connection and handle this issue to at least don' t crash.
Could you try this new debug version please?
https://aumm.black-dragon131.de/AmongUsModManager_debug.exe

**Comment by y-blip** [comment]
ah i'm on windows 7 that might be the issue but let me try the debug

**Comment by y-blip** [comment]
ok The fixed code works

**Comment by Black-Dragon131** [comment]
Nice to hear :)
If I' m correct Windows 7 doesn' t use TLS 1.2 per default (at least in the internet options).
I will add those fixes in the next release. Thanks again for your patience and your feedback :)
